using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tmos.Romhacks.Library.Enum
{
    public enum WSContentType
    {
        Nothing,
        WizardBattleOnEnter,
        FrozenPalace,
        FirstMosque,
        Gilga,
        Gilga2,
        Curly,
        Curly2,
        Troll,
        Troll2,
        Salamander,
        Salamander2,
        GoraGora,
        GoraGora2,
        University_40, //Should Universities be combined?
        University_41,
        University_42,
        University_43,
        University_44,
        University_50,
        University_55,
        Shop_60, //Should Shops be combined?
        Shop_61,
        Shop_62,
        Shop_63,
        Shop_64,
        Shop_65,
        Shop_66,
        Shop_7B,
        Shop_7C,
        Shop_7D,
        Mosque,
        Troopers,
        Jad,
        Faruk,
        Dogos,
        Kebabu,
        AquaPalace,
        WiseManMonecom,
        AchelatoPrincess,
        SabaronTalk,
        GunMeca,
        Lah,
        Supica,
        Epin,
        WisemanRaincome,
        Princess1,
        Princess2,
        NewBornCimaronTree,
        CimaronTree,
		WiseManSpricom,
		Supapa,
        Mustafa,
        FrozenPalace2,
        Gubibi,
        Rainy,
        YuflaPalace,
        Rostam,
        KingFiesal,
        WisemanMoscome,
        Hasan,
        Kaji,
        LegendSword,
        ArmorofLight,
        PalaceEntrance,
        SabaronFinal,
        OnlyOneJarYouCanGoThrough,
        RupiasLady,
        Rupias,
        Hotel_A0,
        Hotel_A1,
        Hotel_A2,
        Hotel_A3,
        Hotel_A4,
        Hotel_A5,
        Hotel_A6,
        Hotel_A7,
        Hotel_A8,
        Hotel_A9,
        Hotel_B0,
        RupiaSeedPlant,
        RupiaTree_BD,
        Casino_1_BE,
        TimeDoorEnter,
        TimeDoorExit_C7,
        TimeDoorExit,
        Battle,
        Other
    }

}
